### ISSUE TITLE
[db] sql: Scan error on column index 0, name \"SUM(Size)\": converting NULL to int64 is unsupported", mailpit | panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by alexszilagyi** [axllent/mailpit#263]
Hi there,

I have encountered the following issue:

```
mailpit         | time="2024/03/09 06:40:08" level=error msg="[db] sql: Scan error on column index 0, name \"SUM(Size)\": converting NULL to int64 is unsupported"
mailpit         | panic: runtime error: integer divide by zero
mailpit         | 
mailpit         | goroutine 6 [running]:
mailpit         | github.com/axllent/mailpit/internal/storage.dbCron()
mailpit         | 	/app/internal/storage/cron.go:30 +0x18f
mailpit         | created by github.com/axllent/mailpit/internal/storage.InitDB in goroutine 1
mailpit         | 	/app/internal/storage/database.go:94 +0x4a5
mailpit exited with code 2
```

It seems that the issues is [somewhere at this line](https://github.com/axllent/mailpit/blob/develop/internal/storage/cron.go#L30). Any ideas how to fix this?

I am using the latest version of mailpit. `axllent/mailpit:latest` docker image.

**Comment by axllent** [comment]
Can you please tell me when this error happens... Is it immediately when Mailpit is started, or after running for 5 minutes?

**Comment by alexszilagyi** [comment]
@axllent I am using in a CI/CD pipeline, after a certain amount of time. Can’t tell you exactly sure. Definitely not immediately
